name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Package
        run: |
          yarn
          yarn build
          yarn pack --filename m6c-memes.tgz
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: m6c-memes-${{ github.sha }}
          path: m6c-memes.tgz
